### ISSUE TITLE
Failing action runs due to FileNotFoundException

### ISSUE THREAD

**Issue by FriedrichFroebel** [sormuras/download-jdk#13]
While refactoring your `bach` repository, it seems like this action got broken:

```lang-none
Run sormuras/download-jdk@v1
Download JDK 14 (linux-x64)
Exception in thread "main" java.io.FileNotFoundException: https://github.com/sormuras/bach/raw/HEAD/install-jdk.properties
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1140)
	at DownloadJDK.browse(DownloadJDK.java:42)
	at DownloadJDK.main(DownloadJDK.java:20)
Error: Process completed with exit code 1.
```

**Comment by sormuras** [comment]
Hi @FriedrichFroebel -- the action should be fixed on `@main`. Updating the `@v1` ref later.
