### ISSUE TITLE
Action  failing on windows with socket timeout error.

### ISSUE THREAD

**Issue by sureshg** [sormuras/download-jdk#24]
Since the last two days, `download-JDK` action failing on the `windows-latest` image with the connect reset error. Nw sure what's causing this error.

```
Run sormuras/download-jdk@v1
  with:
    feature: Loom
  env:
    GITHUB_PUBLISH: false
Run echo "::set-output name=file::JDK_ARCHIVE_NOT_DOWNLOADED_YET"
  echo "::set-output name=file::JDK_ARCHIVE_NOT_DOWNLOADED_YET"
  echo "::set-output name=version::UNKNOWN_VERSION"
  "${JAVA_HOME_11_X64}/bin/java" "D:\a\_actions\sormuras\download-jdk\v1/java/DownloadJDK.java" Loom
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_PUBLISH: false
Download JDK loom (windows-x64)
Exception in thread "main" java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at DownloadJDK.browse(DownloadJDK.java:100)
	at DownloadJDK.parse(DownloadJDK.java:126)
	at DownloadJDK.computeUri(DownloadJDK.java:84)
	at DownloadJDK.main(DownloadJDK.java:26)
Error: Process completed with exit code 1.
```

**Comment by sormuras** [comment]
Usually, this is due to either `jdk.java.net` being "down" or something's off with the `windows-latest` nodes at GH. My bet is on the latter, as I did see a bunch off problems with GH Actions the past days as well...

...anyway, a restart of your workflows might help. Running a self-test of this action as well: https://github.com/sormuras/download-jdk/actions/runs/1735260388

**Comment by sormuras** [comment]
It could also mean, that a new EA version is rolling out...

**Comment by sureshg** [comment]
> jdk.java.net being "down"

I am trying to download the `loom` build. Would have avoided it if this is just one of the cases, but the download is failing continuously for all builds since last few days.

By the way, I am using `sormuras/download-jdk@v1` as given in the example.

**Comment by sormuras** [comment]
🤔 ... works on "my" `windows-latest`, according to the self-test started above.

![image](https://user-images.githubusercontent.com/2319838/150911307-7e4f818b-12b9-4014-b55b-30bad3aba0ec.png)

May I see the workflow configuration file and the entire output of the run?

**Comment by sormuras** [comment]
Seems like this https://github.com/sureshg/openjdk-playground/commit/072eb416925ee416358335f7414629cf9120b42c did help.

**Comment by sureshg** [comment]
I was using v1 all the time. Just changed it for testing as it is mentioned as the latest one in the [GH marketplace](https://github.com/marketplace/actions/download-jdk).  
By the way, seems like the latest build is fine.

**Comment by sureshg** [comment]
I will close it now...  Thanks for looking into this 🙏🏼

**Comment by sormuras** [comment]
Now, all Loom-related archives are returning a 404 HTTP error code... something's off here/there.

```
(HEAD https://download.java.net/java/early_access/loom/1/openjdk-19-loom+1-11_linux-x64_bin.tar.gz) 404
(HEAD https://download.java.net/java/early_access/loom/1/openjdk-19-loom+1-11_macos-x64_bin.tar.gz) 404
(HEAD https://download.java.net/java/early_access/loom/1/openjdk-19-loom+1-11_windows-x64_bin.zip) 404
```
